


const universidades  = [
  {
    nombre: "Universidad Central del Ecuador",
    lat: -0.20146999016143616,
    lng: -78.50731041894979,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Es la universidad más antigua del país y una de las más grandes, con una oferta académica variada en múltiples áreas del conocimiento.",
    fundacion: 1826,
    estudiantes: 40000,
    principalesCarreras: ["Medicina", "Derecho", "Ingeniería", "Ciencias Sociales"],
    sitioWeb: "https://www.uce.edu.ec/",
  },
  {
    nombre: "Universidad Técnica Particular de Loja (UTPL)",
    lat: -3.9867747471515154,
    lng: -79.1993688901226,
    ciudad: "Loja",
    tipo: "Privada",
    descripcion:
      "Institución líder en educación a distancia en Ecuador, reconocida por su enfoque en innovación tecnológica y formación humanista.",
    fundacion: 1971,
    estudiantes: 50000,
    principalesCarreras: ["Educación", "Ingeniería", "Comunicación", "Administración"],
    sitioWeb: "https://www.utpl.edu.ec/",
  },
  {
    nombre: "ESPOL (Escuela Superior Politécnica del Litoral)",
    lat: -2.1774209289811757,
    lng: -79.87949572608926,
    ciudad: "Guayaquil",
    tipo: "Pública",
    descripcion:
      "Institución de prestigio especializada en ciencia, tecnología, ingeniería y matemáticas, con gran enfoque en investigación.",
    fundacion: 1958,
    estudiantes: 18000,
    principalesCarreras: ["Ingeniería en Computación", "Ingeniería Mecánica", "Economía", "Ciencias Naturales"],
    sitioWeb: "https://www.espol.edu.ec/",
  },
  {
    nombre: "Universidad de las Américas (UDLA)",
    lat: -0.16113904294462808,
    lng: -78.45950338592088,
    ciudad: "Quito",
    tipo: "Privada",
    descripcion:
      "Universidad moderna con una fuerte presencia en comunicación, medicina, negocios y arquitectura.",
    fundacion: 1995,
    estudiantes: 15000,
    principalesCarreras: ["Comunicación", "Medicina", "Arquitectura", "Negocios"],
    sitioWeb: "https://www.udla.edu.ec/",
  },
  {
    nombre: "Universidad San Francisco de Quito (USFQ)",
    lat: -0.162,
    lng: -78.4935,
    ciudad: "Quito (Cumbayá)",
    tipo: "Privada",
    descripcion:
      "Universidad liberal con fuerte énfasis en artes, ciencias sociales y biológicas, reconocida por su campus y enfoque internacional.",
    fundacion: 1988,
    estudiantes: 10000,
    principalesCarreras: ["Biología", "Artes Liberales", "Ingeniería Ambiental", "Medicina Veterinaria"],
    sitioWeb: "https://www.usfq.edu.ec/",
  },
  // ... otras universidades e institutos ...
  {
    nombre: "Instituto Superior Tecnológico Sudamericano",
    lat: -3.9952,
    lng: -79.1998,
    ciudad: "Loja",
    tipo: "Privado",
    descripcion:
      "Institución técnica privada con programas modernos en administración, tecnología y comunicación.",
    fundacion: 2001,
    estudiantes: 2000,
    principalesCarreras: ["Administración", "Marketing", "Sistemas", "Comunicación"],
    sitioWeb: "https://sudamericano.edu.ec/",
  },
    {
    nombre: "Universidad Técnica de Ambato (UTA)",
    lat: -1.243629,
    lng: -78.619681,
    ciudad: "Ambato",
    tipo: "Pública",
    descripcion:
      "Universidad reconocida por su formación técnica y científica, con presencia regional importante en Tungurahua.",
    fundacion: 1969,
    estudiantes: 22000,
    principalesCarreras: ["Ingeniería Industrial", "Economía", "Educación", "Agronomía"],
    sitioWeb: "https://www.uta.edu.ec/",
  },
  {
    nombre: "Universidad del Azuay (UDA)",
    lat: -2.897162,
    lng: -79.009199,
    ciudad: "Cuenca",
    tipo: "Privada",
    descripcion:
      "Universidad cuencana con enfoque en calidad educativa, innovación y compromiso social.",
    fundacion: 1968,
    estudiantes: 8000,
    principalesCarreras: ["Arquitectura", "Psicología", "Ingeniería Comercial", "Diseño Gráfico"],
    sitioWeb: "https://www.uazuay.edu.ec/",
  },
  {
    nombre: "Universidad Politécnica Salesiana (UPS)",
    lat: -2.902898,
    lng: -79.014944,
    ciudad: "Cuenca (también en Quito y Guayaquil)",
    tipo: "Privada",
    descripcion:
      "Universidad con fuerte enfoque en inclusión, educación técnica y formación integral.",
    fundacion: 1994,
    estudiantes: 27000,
    principalesCarreras: ["Ingeniería Electrónica", "Psicología", "Administración", "Educación"],
    sitioWeb: "https://www.ups.edu.ec/",
  },
  {
    nombre: "Universidad Estatal de Milagro (UNEMI)",
    lat: -2.132929,
    lng: -79.591191,
    ciudad: "Milagro",
    tipo: "Pública",
    descripcion:
      "Institución pública joven con crecimiento en áreas de salud, tecnología y administración.",
    fundacion: 2001,
    estudiantes: 16000,
    principalesCarreras: ["Enfermería", "Tecnologías de la Información", "Contabilidad", "Educación"],
    sitioWeb: "https://www.unemi.edu.ec/",
  },
  {
    nombre: "Universidad Nacional de Chimborazo (UNACH)",
    lat: -1.674012,
    lng: -78.654993,
    ciudad: "Riobamba",
    tipo: "Pública",
    descripcion:
      "Centro académico regional con fuerte desarrollo en salud, educación y ciencias puras.",
    fundacion: 1995,
    estudiantes: 15000,
    principalesCarreras: ["Medicina", "Educación", "Ingeniería en Sistemas", "Biología"],
    sitioWeb: "https://www.unach.edu.ec/",
  },
  {
    nombre: "Universidad de Guayaquil",
    lat: -2.1972,
    lng: -79.8832,
    ciudad: "Guayaquil",
    tipo: "Pública",
    descripcion:
      "Una de las mayores del país, con amplia oferta en ciencias, humanidades, salud, ingeniería y artes.",
    fundacion: 1883,
    estudiantes: 40000,
    principalesCarreras: ["Medicina", "Derecho", "Ingeniería Civil", "Artes"],
    sitioWeb: "https://www.ug.edu.ec/",
  },
  {
    nombre: "Escuela Superior Politécnica Nacional (EPN)",
    lat: -0.1807,
    lng: -78.4678,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Principal institución técnica y tecnológica del Ecuador, enfocada en ingeniería, ciencias y desarrollo tecnológico.",
    fundacion: 1869,
    estudiantes: 15000,
    principalesCarreras: ["Ingeniería Eléctrica", "Computación", "Telecomunicaciones", "Biotecnología"],
    sitioWeb: "https://www.epn.edu.ec/",
  },
  {
    nombre: "Universidad de las Fuerzas Armadas (ESPE)",
    lat: -0.3250,
    lng: -78.2333,
    ciudad: "Sangolquí (Pichincha)",
    tipo: "Pública",
    descripcion:
      "Universidad especializada en formación militar y civil, con fuerte enfoque en ingeniería y ciencias de la seguridad.",
    fundacion: 1922,
    estudiantes: 8000,
    principalesCarreras: ["Ingeniería Aeroespacial", "Seguridad", "Gestión de Riesgos", "Derecho"],
    sitioWeb: "https://www.espe.edu.ec/",
  },
  {
    nombre: "Universidad Andina Simón Bolívar (UASB)",
    lat: -0.1800,
    lng: -78.4794,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Institución internacional regional con sede en Ecuador, enfocada en posgrados y estudios sociales y ambientales.",
    fundacion: 1985,
    estudiantes: 1000,
    principalesCarreras: ["Relaciones Internacionales", "Política Pública", "Gestión Ambiental", "Derecho"],
    sitioWeb: "https://www.uasb.edu.ec/",
  },

  // Universidades privadas destacadas adicionales
  {
    nombre: "Universidad Internacional del Ecuador (UIDE)",
    lat: -0.1550,
    lng: -78.4550,
    ciudad: "Quito",
    tipo: "Privada",
    descripcion:
      "Institución privada con enfoque integral en salud, derecho, negocios y humanidades.",
    fundacion: 1993,
    estudiantes: 12000,
    principalesCarreras: ["Medicina", "Odontología", "Derecho", "Negocios"],
    sitioWeb: "https://www.uide.edu.ec/",
  },
  {
    nombre: "Universidad Espíritu Santo (UEES)",
    lat: -2.1560,
    lng: -79.8770,
    ciudad: "Guayaquil",
    tipo: "Privada",
    descripcion:
      "Universidad internacional privada con amplia oferta en negocios, derecho, hospitalidad y ciencias sociales.",
    fundacion: 1994,
    estudiantes: 5000,
    principalesCarreras: ["Administración de Empresas", "Derecho", "Hospitalidad", "Comunicación"],
    sitioWeb: "https://www.uees.edu.ec/",
  },
  {
    nombre: "Universidad Católica de Cuenca (UCACUE)",
    lat: -2.9000,
    lng: -79.0030,
    ciudad: "Cuenca",
    tipo: "Privada",
    descripcion:
      "Universidad católica regional centrada en educación, salud, derecho, turismo y humanidades.",
    fundacion: 1970,
    estudiantes: 6000,
    principalesCarreras: ["Educación", "Medicina", "Derecho", "Turismo"],
    sitioWeb: "https://www.ucacue.edu.ec/",
  },

  // Institutos superiores técnicos y tecnológicos
  {
    nombre: "Instituto Superior Tecnológico Guayaquil",
    lat: -2.1833,
    lng: -79.9000,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto reconocido por programas técnicos en gestión, sistemas y electromecánica.",
    fundacion: 1990,
    estudiantes: 3000,
    principalesCarreras: ["Tecnología en Sistemas", "Administración", "Electromecánica"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Vicente Rocafuerte",
    lat: -2.1930,
    lng: -79.9070,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto histórico en formación técnica en comercio, áreas sociales y tecnologías.",
    fundacion: 1958,
    estudiantes: 2500,
    principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Juan Bautista Aguirre",
    lat: -2.1470,
    lng: -79.8950,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto con programas técnicos en administración turística, negocios y servicios.",
    fundacion: 1965,
    estudiantes: 2000,
    principalesCarreras: ["Gestión Turística", "Administración", "Marketing"],
    sitioWeb: "",
  },
  {
  nombre: "Universidad Internacional del Ecuador (UIDE)",
  lat: -0.1550,
  lng: -78.4550,
  ciudad: "Quito",
  tipo: "Privada",
  descripcion:
    "Institución privada con enfoque integral en salud, derecho, negocios y humanidades.",
  fundacion: 1993,
  estudiantes: 12000,
  principalesCarreras: ["Medicina", "Odontología", "Derecho", "Negocios"],
  sitioWeb: "https://www.uide.edu.ec/",
},
{
  nombre: "Universidad Espíritu Santo (UEES)",
  lat: -2.1560,
  lng: -79.8770,
  ciudad: "Guayaquil",
  tipo: "Privada",
  descripcion:
    "Universidad internacional privada con amplia oferta en negocios, derecho, hospitalidad y ciencias sociales.",
  fundacion: 1994,
  estudiantes: 5000,
  principalesCarreras: ["Administración de Empresas", "Derecho", "Hospitalidad", "Comunicación"],
  sitioWeb: "https://www.uees.edu.ec/",
},
{
  nombre: "Universidad Católica de Cuenca (UCACUE)",
  lat: -2.9000,
  lng: -79.0030,
  ciudad: "Cuenca",
  tipo: "Privada",
  descripcion:
    "Universidad católica regional centrada en educación, salud, derecho, turismo y humanidades.",
  fundacion: 1970,
  estudiantes: 6000,
  principalesCarreras: ["Educación", "Medicina", "Derecho", "Turismo"],
  sitioWeb: "https://www.ucacue.edu.ec/",
},
{
  nombre: "Instituto Superior Tecnológico Guayaquil",
  lat: -2.1833,
  lng: -79.9000,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto reconocido por programas técnicos en gestión, sistemas y electromecánica.",
  fundacion: 1990,
  estudiantes: 3000,
  principalesCarreras: ["Tecnología en Sistemas", "Administración", "Electromecánica"],
  sitioWeb: "",
},
{
  nombre: "Instituto Superior Tecnológico Vicente Rocafuerte",
  lat: -2.1930,
  lng: -79.9070,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto histórico en formación técnica en comercio, áreas sociales y tecnologías.",
  fundacion: 1958,
  estudiantes: 2500,
  principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
  sitioWeb: "",
},
{
  nombre: "Instituto Superior Tecnológico Juan Bautista Aguirre",
  lat: -2.1470,
  lng: -79.8950,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto con programas técnicos en administración turística, negocios y servicios.",
  fundacion: 1965,
  estudiantes: 2000,
  principalesCarreras: ["Gestión Turística", "Administración", "Marketing"],
  sitioWeb: "",
},
{
    nombre: "Universidad Católica de Santiago de Guayaquil (UCSG)",
    lat: -2.1962,
    lng: -79.9007,
    ciudad: "Guayaquil",
    tipo: "Privada",
    descripcion:
      "Universidad católica reconocida por su excelencia académica y compromiso social, con programas en salud, ingeniería, derecho y humanidades.",
    fundacion: 1962,
    estudiantes: 14000,
    principalesCarreras: ["Medicina", "Ingeniería Civil", "Derecho", "Psicología"],
    sitioWeb: "https://www.ucsg.edu.ec/",
  },
  {
    nombre: "Universidad Estatal Amazónica (UNAE)",
    lat: -1.0351,
    lng: -77.4848,
    ciudad: "Puyo",
    tipo: "Pública",
    descripcion:
      "Universidad pública con enfoque en el desarrollo sostenible, biodiversidad y cultura amazónica.",
    fundacion: 2002,
    estudiantes: 3500,
    principalesCarreras: ["Biología", "Ingeniería Forestal", "Turismo", "Derecho"],
    sitioWeb: "https://www.unae.edu.ec/",
  },
  {
    nombre: "Universidad Técnica del Norte (UTN)",
    lat: 0.3337,
    lng: -78.1231,
    ciudad: "Ibarra",
    tipo: "Pública",
    descripcion:
      "Institución pública orientada a la formación técnica y científica en el norte del país.",
    fundacion: 1981,
    estudiantes: 7000,
    principalesCarreras: ["Ingeniería Agronómica", "Medicina Veterinaria", "Computación", "Administración"],
    sitioWeb: "https://www.utn.edu.ec/",
  },
  {
    nombre: "Universidad Regional Autónoma de los Andes (UNIANDES)",
    lat: -1.0001,
    lng: -78.6168,
    ciudad: "Ambato",
    tipo: "Privada",
    descripcion:
      "Universidad privada regional con énfasis en salud, ciencias administrativas y jurídicas.",
    fundacion: 1996,
    estudiantes: 5000,
    principalesCarreras: ["Medicina", "Administración", "Derecho", "Psicología"],
    sitioWeb: "https://www.uniandes.edu.ec/",
  },
  {
    nombre: "Universidad Estatal Península de Santa Elena (UPSE)",
    lat: -2.2186,
    lng: -80.9339,
    ciudad: "La Libertad",
    tipo: "Pública",
    descripcion:
      "Universidad pública enfocada en desarrollo regional y carreras de ciencias aplicadas.",
    fundacion: 1998,
    estudiantes: 8000,
    principalesCarreras: ["Ingeniería Pesquera", "Administración", "Turismo", "Contabilidad"],
    sitioWeb: "https://www.upse.edu.ec/",
  },
  {
    nombre: "Universidad Técnica Luis Vargas Torres de Esmeraldas (UTLVTE)",
    lat: 0.9774,
    lng: -79.6531,
    ciudad: "Esmeraldas",
    tipo: "Pública",
    descripcion:
      "Universidad pública con enfoque en ingeniería y ciencias sociales en la región costa norte.",
    fundacion: 1986,
    estudiantes: 9000,
    principalesCarreras: ["Ingeniería Civil", "Derecho", "Administración", "Agronomía"],
    sitioWeb: "https://www.utlvte.edu.ec/",
  },
  {
    nombre: "Universidad Técnica Estatal de Quevedo (UTEQ)",
    lat: -1.0339,
    lng: -79.4669,
    ciudad: "Quevedo",
    tipo: "Pública",
    descripcion:
      "Institución técnica y tecnológica que ofrece carreras en ingeniería y administración con enfoque regional.",
    fundacion: 1984,
    estudiantes: 6000,
    principalesCarreras: ["Ingeniería Industrial", "Agronomía", "Contabilidad", "Informática"],
    sitioWeb: "https://www.uteq.edu.ec/",
  },
  {
    nombre: "Universidad del Pacífico - Ecuador",
    lat: -2.2001,
    lng: -79.8965,
    ciudad: "Guayaquil",
    tipo: "Privada",
    descripcion:
      "Universidad privada enfocada en negocios, economía, derecho y ciencias sociales, con vinculación internacional.",
    fundacion: 1995,
    estudiantes: 4000,
    principalesCarreras: ["Negocios Internacionales", "Economía", "Derecho", "Comunicación"],
    sitioWeb: "https://www.upacifico.edu.ec/",
  },
  {
    nombre: "Universidad Laica Eloy Alfaro de Manabí (ULEAM)",
    lat: -0.9551,
    lng: -80.7112,
    ciudad: "Portoviejo",
    tipo: "Pública",
    descripcion:
      "Universidad pública con amplia oferta académica y presencia en Manabí, con énfasis en ciencias sociales, salud e ingeniería.",
    fundacion: 1978,
    estudiantes: 15000,
    principalesCarreras: ["Medicina", "Ingeniería Civil", "Derecho", "Educación"],
    sitioWeb: "https://www.uleam.edu.ec/",
  },
  {
    nombre: "Escuela Superior Politécnica Agropecuaria de Manabí (ESPAM)",
    lat: -0.9552,
    lng: -80.7124,
    ciudad: "Portoviejo",
    tipo: "Pública",
    descripcion:
      "Institución pública especializada en carreras agropecuarias y ambientales.",
    fundacion: 1978,
    estudiantes: 4500,
    principalesCarreras: ["Agronomía", "Ingeniería Ambiental", "Biotecnología"],
    sitioWeb: "https://www.espam.edu.ec/",
  },
  {
  nombre: "Universidad Internacional del Ecuador (UIDE) - Sede Loja",
  lat: -3.9718452224069782,
  lng: -79.19910574744131,
  ciudad: "Loja",
  tipo: "Privada",
  descripcion:
    "Extensión de la UIDE en Loja, con oferta académica orientada a las necesidades regionales, combinando formación integral y tecnológica.",
  fundacion: 2010, // año aproximado, ya que es sede relativamente nueva -3.9718452224069782, -79.19910574744131
  estudiantes: 1500, // estimado, puede variar
  principalesCarreras: ["Administración de Empresas", "Ingeniería en Sistemas", "Comunicación", "Derecho"],
  sitioWeb: "https://www.uide.edu.ec/sede-loja",
},
{
    nombre: "Instituto Superior Tecnológico Don Bosco",
    lat: -0.1719,
    lng: -78.4814,
    ciudad: "Quito",
    tipo: "Privado",
    descripcion:
      "Instituto con fuerte orientación técnica en áreas industriales, administrativas y tecnológicas, reconocido a nivel nacional.",
    fundacion: 1981,
    estudiantes: 4000,
    principalesCarreras: ["Electrónica", "Mecánica", "Administración", "Sistemas"],
    sitioWeb: "https://www.donbosco.edu.ec/",
  },
  {
    nombre: "Instituto Superior Tecnológico Rumiñahui",
    lat: -0.1912,
    lng: -78.4900,
    ciudad: "Quito",
    tipo: "Privado",
    descripcion:
      "Instituto con programas técnicos enfocados en sistemas, administración y turismo.",
    fundacion: 1993,
    estudiantes: 2500,
    principalesCarreras: ["Sistemas", "Administración", "Turismo"],
    sitioWeb: "https://ruminahui.edu.ec/",
  },
  {
    nombre: "Instituto Superior Tecnológico Simón Bolívar",
    lat: -2.1956,
    lng: -79.9008,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto técnico reconocido por su formación en comercio, administración y tecnología.",
    fundacion: 1985,
    estudiantes: 3000,
    principalesCarreras: ["Comercio", "Administración", "Tecnología en Sistemas"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico San Francisco de Quito",
    lat: -0.162,
    lng: -78.4935,
    ciudad: "Quito",
    tipo: "Privado",
    descripcion:
      "Instituto con programas técnicos vinculados a la educación y tecnología.",
    fundacion: 1990,
    estudiantes: 1200,
    principalesCarreras: ["Educación", "Tecnología"],
    sitioWeb: "https://www.usfq.edu.ec/",
  },
  {
    nombre: "Instituto Superior Tecnológico Panamericano",
    lat: -2.155,
    lng: -79.887,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto con formación técnica en administración, comercio y sistemas.",
    fundacion: 1992,
    estudiantes: 2200,
    principalesCarreras: ["Administración", "Comercio", "Sistemas"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Nacional San Bartolomé",
    lat: -2.183,
    lng: -79.899,
    ciudad: "Guayaquil",
    tipo: "Público",
    descripcion:
      "Instituto público técnico con formación en áreas de comercio y tecnología.",
    fundacion: 1980,
    estudiantes: 3500,
    principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
    sitioWeb: "",
  },

  {
    nombre: "Instituto Superior Tecnológico Guayaquil",
    lat: -2.1833,
    lng: -79.9000,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto reconocido por programas técnicos en gestión, sistemas y electromecánica.",
    fundacion: 1990,
    estudiantes: 3000,
    principalesCarreras: ["Tecnología en Sistemas", "Administración", "Electromecánica"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Vicente Rocafuerte",
    lat: -2.1930,
    lng: -79.9070,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto histórico en formación técnica en comercio, áreas sociales y tecnologías.",
    fundacion: 1958,
    estudiantes: 2500,
    principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Juan Bautista Aguirre",
    lat: -2.1470,
    lng: -79.8950,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto con programas técnicos en administración turística, negocios y servicios.",
    fundacion: 1965,
    estudiantes: 2000,
    principalesCarreras: ["Gestión Turística", "Administración", "Marketing"],
    sitioWeb: "",
  },
  {
  nombre: "Universidad Nacional de Loja (UNL)",
  lat: -4.0061,
  lng: -79.2043,
  ciudad: "Loja",
  tipo: "Pública",
  descripcion:
    "Universidad pública regional con fuerte énfasis en investigación, ciencias sociales, educación y tecnología.",
  fundacion: 2000,
  estudiantes: 9000, // estimado
  principalesCarreras: ["Educación", "Derecho", "Ingeniería en Sistemas", "Ciencias Sociales"],
  sitioWeb: "https://www.unl.edu.ec/",
},

];

export default universidades;