


const universidades  = [
  {
    nombre: "Universidad Central del Ecuador",
    lat: -0.20146999016143616,
    lng: -78.50731041894979,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Es la universidad más antigua del país y una de las más grandes, con una oferta académica variada en múltiples áreas del conocimiento.",
    fundacion: 1826,
    estudiantes: 40000,
    principalesCarreras: ["Medicina", "Derecho", "Ingeniería", "Ciencias Sociales"],
    sitioWeb: "https://www.uce.edu.ec/",
  },
  {
    nombre: "Universidad Técnica Particular de Loja (UTPL)",
    lat: -3.9867747471515154,
    lng: -79.1993688901226,
    ciudad: "Loja",
    tipo: "Privada",
    descripcion:
      "Institución líder en educación a distancia en Ecuador, reconocida por su enfoque en innovación tecnológica y formación humanista.",
    fundacion: 1971,
    estudiantes: 50000,
    principalesCarreras: ["Educación", "Ingeniería", "Comunicación", "Administración"],
    sitioWeb: "https://www.utpl.edu.ec/",
  },
  {
    nombre: "ESPOL (Escuela Superior Politécnica del Litoral)",
    lat: -2.1774209289811757,
    lng: -79.87949572608926,
    ciudad: "Guayaquil",
    tipo: "Pública",
    descripcion:
      "Institución de prestigio especializada en ciencia, tecnología, ingeniería y matemáticas, con gran enfoque en investigación.",
    fundacion: 1958,
    estudiantes: 18000,
    principalesCarreras: ["Ingeniería en Computación", "Ingeniería Mecánica", "Economía", "Ciencias Naturales"],
    sitioWeb: "https://www.espol.edu.ec/",
  },
  {
    nombre: "Universidad de las Américas (UDLA)",
    lat: -0.16113904294462808,
    lng: -78.45950338592088,
    ciudad: "Quito",
    tipo: "Privada",
    descripcion:
      "Universidad moderna con una fuerte presencia en comunicación, medicina, negocios y arquitectura.",
    fundacion: 1995,
    estudiantes: 15000,
    principalesCarreras: ["Comunicación", "Medicina", "Arquitectura", "Negocios"],
    sitioWeb: "https://www.udla.edu.ec/",
  },
  {
    nombre: "Universidad San Francisco de Quito (USFQ)",
    lat: -0.162,
    lng: -78.4935,
    ciudad: "Quito (Cumbayá)",
    tipo: "Privada",
    descripcion:
      "Universidad liberal con fuerte énfasis en artes, ciencias sociales y biológicas, reconocida por su campus y enfoque internacional.",
    fundacion: 1988,
    estudiantes: 10000,
    principalesCarreras: ["Biología", "Artes Liberales", "Ingeniería Ambiental", "Medicina Veterinaria"],
    sitioWeb: "https://www.usfq.edu.ec/",
  },
  // ... otras universidades e institutos ...
  {
    nombre: "Instituto Superior Tecnológico Sudamericano",
    lat: -3.9952,
    lng: -79.1998,
    ciudad: "Loja",
    tipo: "Privado",
    descripcion:
      "Institución técnica privada con programas modernos en administración, tecnología y comunicación.",
    fundacion: 2001,
    estudiantes: 2000,
    principalesCarreras: ["Administración", "Marketing", "Sistemas", "Comunicación"],
    sitioWeb: "https://sudamericano.edu.ec/",
  },
    {
    nombre: "Universidad Técnica de Ambato (UTA)",
    lat: -1.243629,
    lng: -78.619681,
    ciudad: "Ambato",
    tipo: "Pública",
    descripcion:
      "Universidad reconocida por su formación técnica y científica, con presencia regional importante en Tungurahua.",
    fundacion: 1969,
    estudiantes: 22000,
    principalesCarreras: ["Ingeniería Industrial", "Economía", "Educación", "Agronomía"],
    sitioWeb: "https://www.uta.edu.ec/",
  },
  {
    nombre: "Universidad del Azuay (UDA)",
    lat: -2.897162,
    lng: -79.009199,
    ciudad: "Cuenca",
    tipo: "Privada",
    descripcion:
      "Universidad cuencana con enfoque en calidad educativa, innovación y compromiso social.",
    fundacion: 1968,
    estudiantes: 8000,
    principalesCarreras: ["Arquitectura", "Psicología", "Ingeniería Comercial", "Diseño Gráfico"],
    sitioWeb: "https://www.uazuay.edu.ec/",
  },
  {
    nombre: "Universidad Politécnica Salesiana (UPS)",
    lat: -2.902898,
    lng: -79.014944,
    ciudad: "Cuenca (también en Quito y Guayaquil)",
    tipo: "Privada",
    descripcion:
      "Universidad con fuerte enfoque en inclusión, educación técnica y formación integral.",
    fundacion: 1994,
    estudiantes: 27000,
    principalesCarreras: ["Ingeniería Electrónica", "Psicología", "Administración", "Educación"],
    sitioWeb: "https://www.ups.edu.ec/",
  },
  {
    nombre: "Universidad Estatal de Milagro (UNEMI)",
    lat: -2.132929,
    lng: -79.591191,
    ciudad: "Milagro",
    tipo: "Pública",
    descripcion:
      "Institución pública joven con crecimiento en áreas de salud, tecnología y administración.",
    fundacion: 2001,
    estudiantes: 16000,
    principalesCarreras: ["Enfermería", "Tecnologías de la Información", "Contabilidad", "Educación"],
    sitioWeb: "https://www.unemi.edu.ec/",
  },
  {
    nombre: "Universidad Nacional de Chimborazo (UNACH)",
    lat: -1.674012,
    lng: -78.654993,
    ciudad: "Riobamba",
    tipo: "Pública",
    descripcion:
      "Centro académico regional con fuerte desarrollo en salud, educación y ciencias puras.",
    fundacion: 1995,
    estudiantes: 15000,
    principalesCarreras: ["Medicina", "Educación", "Ingeniería en Sistemas", "Biología"],
    sitioWeb: "https://www.unach.edu.ec/",
  },
  {
    nombre: "Universidad de Guayaquil",
    lat: -2.1972,
    lng: -79.8832,
    ciudad: "Guayaquil",
    tipo: "Pública",
    descripcion:
      "Una de las mayores del país, con amplia oferta en ciencias, humanidades, salud, ingeniería y artes.",
    fundacion: 1883,
    estudiantes: 40000,
    principalesCarreras: ["Medicina", "Derecho", "Ingeniería Civil", "Artes"],
    sitioWeb: "https://www.ug.edu.ec/",
  },
  {
    nombre: "Escuela Superior Politécnica Nacional (EPN)",
    lat: -0.1807,
    lng: -78.4678,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Principal institución técnica y tecnológica del Ecuador, enfocada en ingeniería, ciencias y desarrollo tecnológico.",
    fundacion: 1869,
    estudiantes: 15000,
    principalesCarreras: ["Ingeniería Eléctrica", "Computación", "Telecomunicaciones", "Biotecnología"],
    sitioWeb: "https://www.epn.edu.ec/",
  },
  {
    nombre: "Universidad de las Fuerzas Armadas (ESPE)",
    lat: -0.3250,
    lng: -78.2333,
    ciudad: "Sangolquí (Pichincha)",
    tipo: "Pública",
    descripcion:
      "Universidad especializada en formación militar y civil, con fuerte enfoque en ingeniería y ciencias de la seguridad.",
    fundacion: 1922,
    estudiantes: 8000,
    principalesCarreras: ["Ingeniería Aeroespacial", "Seguridad", "Gestión de Riesgos", "Derecho"],
    sitioWeb: "https://www.espe.edu.ec/",
  },
  {
    nombre: "Universidad Andina Simón Bolívar (UASB)",
    lat: -0.1800,
    lng: -78.4794,
    ciudad: "Quito",
    tipo: "Pública",
    descripcion:
      "Institución internacional regional con sede en Ecuador, enfocada en posgrados y estudios sociales y ambientales.",
    fundacion: 1985,
    estudiantes: 1000,
    principalesCarreras: ["Relaciones Internacionales", "Política Pública", "Gestión Ambiental", "Derecho"],
    sitioWeb: "https://www.uasb.edu.ec/",
  },

  // Universidades privadas destacadas adicionales
  {
    nombre: "Universidad Internacional del Ecuador (UIDE)",
    lat: -0.1550,
    lng: -78.4550,
    ciudad: "Quito",
    tipo: "Privada",
    descripcion:
      "Institución privada con enfoque integral en salud, derecho, negocios y humanidades.",
    fundacion: 1993,
    estudiantes: 12000,
    principalesCarreras: ["Medicina", "Odontología", "Derecho", "Negocios"],
    sitioWeb: "https://www.uide.edu.ec/",
  },
  {
    nombre: "Universidad Espíritu Santo (UEES)",
    lat: -2.1560,
    lng: -79.8770,
    ciudad: "Guayaquil",
    tipo: "Privada",
    descripcion:
      "Universidad internacional privada con amplia oferta en negocios, derecho, hospitalidad y ciencias sociales.",
    fundacion: 1994,
    estudiantes: 5000,
    principalesCarreras: ["Administración de Empresas", "Derecho", "Hospitalidad", "Comunicación"],
    sitioWeb: "https://www.uees.edu.ec/",
  },
  {
    nombre: "Universidad Católica de Cuenca (UCACUE)",
    lat: -2.9000,
    lng: -79.0030,
    ciudad: "Cuenca",
    tipo: "Privada",
    descripcion:
      "Universidad católica regional centrada en educación, salud, derecho, turismo y humanidades.",
    fundacion: 1970,
    estudiantes: 6000,
    principalesCarreras: ["Educación", "Medicina", "Derecho", "Turismo"],
    sitioWeb: "https://www.ucacue.edu.ec/",
  },

  // Institutos superiores técnicos y tecnológicos
  {
    nombre: "Instituto Superior Tecnológico Guayaquil",
    lat: -2.1833,
    lng: -79.9000,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto reconocido por programas técnicos en gestión, sistemas y electromecánica.",
    fundacion: 1990,
    estudiantes: 3000,
    principalesCarreras: ["Tecnología en Sistemas", "Administración", "Electromecánica"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Vicente Rocafuerte",
    lat: -2.1930,
    lng: -79.9070,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto histórico en formación técnica en comercio, áreas sociales y tecnologías.",
    fundacion: 1958,
    estudiantes: 2500,
    principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
    sitioWeb: "",
  },
  {
    nombre: "Instituto Superior Tecnológico Juan Bautista Aguirre",
    lat: -2.1470,
    lng: -79.8950,
    ciudad: "Guayaquil",
    tipo: "Privado",
    descripcion:
      "Instituto con programas técnicos en administración turística, negocios y servicios.",
    fundacion: 1965,
    estudiantes: 2000,
    principalesCarreras: ["Gestión Turística", "Administración", "Marketing"],
    sitioWeb: "",
  },
  {
  nombre: "Universidad Internacional del Ecuador (UIDE)",
  lat: -0.1550,
  lng: -78.4550,
  ciudad: "Quito",
  tipo: "Privada",
  descripcion:
    "Institución privada con enfoque integral en salud, derecho, negocios y humanidades.",
  fundacion: 1993,
  estudiantes: 12000,
  principalesCarreras: ["Medicina", "Odontología", "Derecho", "Negocios"],
  sitioWeb: "https://www.uide.edu.ec/",
},
{
  nombre: "Universidad Espíritu Santo (UEES)",
  lat: -2.1560,
  lng: -79.8770,
  ciudad: "Guayaquil",
  tipo: "Privada",
  descripcion:
    "Universidad internacional privada con amplia oferta en negocios, derecho, hospitalidad y ciencias sociales.",
  fundacion: 1994,
  estudiantes: 5000,
  principalesCarreras: ["Administración de Empresas", "Derecho", "Hospitalidad", "Comunicación"],
  sitioWeb: "https://www.uees.edu.ec/",
},
{
  nombre: "Universidad Católica de Cuenca (UCACUE)",
  lat: -2.9000,
  lng: -79.0030,
  ciudad: "Cuenca",
  tipo: "Privada",
  descripcion:
    "Universidad católica regional centrada en educación, salud, derecho, turismo y humanidades.",
  fundacion: 1970,
  estudiantes: 6000,
  principalesCarreras: ["Educación", "Medicina", "Derecho", "Turismo"],
  sitioWeb: "https://www.ucacue.edu.ec/",
},
{
  nombre: "Instituto Superior Tecnológico Guayaquil",
  lat: -2.1833,
  lng: -79.9000,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto reconocido por programas técnicos en gestión, sistemas y electromecánica.",
  fundacion: 1990,
  estudiantes: 3000,
  principalesCarreras: ["Tecnología en Sistemas", "Administración", "Electromecánica"],
  sitioWeb: "",
},
{
  nombre: "Instituto Superior Tecnológico Vicente Rocafuerte",
  lat: -2.1930,
  lng: -79.9070,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto histórico en formación técnica en comercio, áreas sociales y tecnologías.",
  fundacion: 1958,
  estudiantes: 2500,
  principalesCarreras: ["Comercio Exterior", "Contabilidad", "Informática"],
  sitioWeb: "",
},
{
  nombre: "Instituto Superior Tecnológico Juan Bautista Aguirre",
  lat: -2.1470,
  lng: -79.8950,
  ciudad: "Guayaquil",
  tipo: "Privado",
  descripcion:
    "Instituto con programas técnicos en administración turística, negocios y servicios.",
  fundacion: 1965,
  estudiantes: 2000,
  principalesCarreras: ["Gestión Turística", "Administración", "Marketing"],
  sitioWeb: "",
},

];

export default universidades;